import { StoryblokProvider } from './components/config/StoryblokProvider';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Flat carbon steel from thyssenkrupp',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang='en'>
        <body className={`antialiased`}>{children}</body>
      </html>
    </StoryblokProvider>
  );
}
